#!/usr/bin/env python3
"""Generate src/renderer/renderer_geom_presets.mbt from presetShapeDefinitions.xml.

The ECMA-376 preset shape definitions ship with the standard:
  ECMA-376 Part 1, electronic attachment "OfficeOpenXML-DrawingMLGeometries.zip"
  (https://ecma-international.org/publications-and-standards/standards/ecma-376/)
LibreOffice carries the same file at
  oox/source/drawingml/customshapes/presetShapeDefinitions.xml

Usage:
  python3 scripts/gen_preset_geom.py path/to/presetShapeDefinitions.xml
  moon fmt

Each preset becomes a PresetDef of compact strings, parsed once at render time
by renderer_geom.mbt:
  avlst  "name=val;..."            adjust-value defaults, in declaration order
  gdlst  "name=fmla;..."           guide formulas, in evaluation order
  paths  sub-paths joined by "|"   each may start with
                                     W pw ph   the path's own coordinate space
                                     F mode    fill: none / darken / darkenLess /
                                               lighten / lightenLess
                                     S false   the path is not stroked
                                   then M / L / C / Q / A / Z commands
  rect   "l t r b"                 text rectangle guides ("" = the whole shape)
"""

import sys
# The input is the trusted ECMA-376 definition file, read by a developer tool.
import xml.etree.ElementTree as ET
from pathlib import Path

A = "{http://schemas.openxmlformats.org/drawingml/2006/main}"
OUT = Path(__file__).resolve().parent.parent / "src/renderer/renderer_geom_presets.mbt"

# Presets the parser maps to dedicated ShapeGeom kinds (ooxml parse_geom) and
# therefore never looks up here.
DEDICATED = {"rect", "ellipse", "roundRect", "line", "straightConnector1"}

# Non-standard names seen in the wild, rendered as their standard preset.
ALIASES = {
    "can": ["cylinder"],
    "horizontalScroll": ["horzScroll"],
    "plus": ["cross"],
    "triangle": ["isosTriangle"],
    "verticalScroll": ["vertScroll"],
}


def pts(el):
    return " ".join("%s %s" % (p.get("x"), p.get("y")) for p in el.findall(A + "pt"))


def path_cmds(path):
    out = []
    if path.get("w") is not None or path.get("h") is not None:
        out.append("W %s %s" % (path.get("w", "0"), path.get("h", "0")))
    fill = path.get("fill", "norm")
    if fill != "norm":
        out.append("F " + fill)
    if path.get("stroke", "true") in ("false", "0"):
        out.append("S false")
    for c in path:
        tag = c.tag.replace(A, "")
        if tag == "moveTo":
            out.append("M " + pts(c))
        elif tag == "lnTo":
            out.append("L " + pts(c))
        elif tag == "cubicBezTo":
            out.append("C " + pts(c))
        elif tag == "quadBezTo":
            out.append("Q " + pts(c))
        elif tag == "arcTo":
            out.append("A %s %s %s %s" % (c.get("wR"), c.get("hR"), c.get("stAng"), c.get("swAng")))
        elif tag == "close":
            out.append("Z")
        else:
            raise ValueError("unknown path element " + tag)
    return " ".join(out)


def gd_list(parent, only_val=False):
    if parent is None:
        return ""
    items = []
    for g in parent.findall(A + "gd"):
        fmla = g.get("fmla")
        if only_val:
            op, val = fmla.split()
            assert op == "val", fmla
            fmla = val
        items.append("%s=%s" % (g.get("name"), fmla))
    return ";".join(items)


def preset(el):
    rect = el.find(A + "rect")
    rect_s = ""
    if rect is not None:
        rect_s = " ".join(rect.get(k) for k in ("l", "t", "r", "b"))
        if rect_s == "l t r b":
            rect_s = ""
    for s in (gd_list(el.find(A + "gdLst")), rect_s):
        assert '"' not in s and "\\" not in s
    return {
        "avlst": gd_list(el.find(A + "avLst"), only_val=True),
        "gdlst": gd_list(el.find(A + "gdLst")),
        "paths": "|".join(path_cmds(p) for p in el.find(A + "pathLst").findall(A + "path")),
        "rect": rect_s,
    }


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    root = ET.parse(sys.argv[1]).getroot()
    names = sorted(c.tag for c in root if c.tag not in DEDICATED)
    arms = []
    for name in names:
        d = preset(root.find(name))
        pat = " | ".join('"%s"' % n for n in [name] + ALIASES.get(name, []))
        arms.append(
            "    %s =>\n      Some({\n"
            '        avlst: "%s",\n'
            '        gdlst: "%s",\n'
            '        paths: "%s",\n'
            '        rect: "%s",\n'
            "      })" % (pat, d["avlst"], d["gdlst"], d["paths"], d["rect"])
        )
    src = (
        "// Code generated by scripts/gen_preset_geom.py from the ECMA-376\n"
        "// presetShapeDefinitions.xml. DO NOT EDIT — regenerate instead.\n"
        "//\n"
        "// String formats are described in the generator and parsed by renderer_geom.mbt.\n"
        "\n"
        "///|\n"
        "/// Look up a preset shape definition by name (%d presets).\n"
        "fn get_preset_def(prst : String) -> PresetDef? {\n"
        "  match prst {\n%s\n    _ => None\n  }\n}\n" % (len(names), "\n".join(arms))
    )
    OUT.write_text(src)
    print("wrote %s (%d presets)" % (OUT, len(names)))


if __name__ == "__main__":
    main()
